{% set name = "crontab" %}
{% set version = "0.23.0" %}
{% set sha256 = "ca79dede9c2f572bb32f38703e8fddcf3427e86edc838f2ffe7ae4b9ee2b0733" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - crontab

about:
  home: https://github.com/josiahcarlson/parse-crontab
  license: LGPL-2.1 or LGPL-3.0
  license_family: LGPL
  license_file: LICENSE3
  summary: Parse and use crontab schedules in Python

extra:
  recipe-maintainers:
    - mcs07
