{% set name = "crontab" %}
{% set version = "0.22.9" %}
{% set sha256 = "9678e38bcd7f3e51a3b9a0ce8ebeff2b4ab2d9fe629186cb5a896ccad85fd3d0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - crontab

about:
  home: https://github.com/josiahcarlson/parse-crontab
  license: LGPL-2.1 or LGPL-3.0
  license_family: LGPL
  license_file: LICENSE3
  summary: Parse and use crontab schedules in Python

extra:
  recipe-maintainers:
    - mcs07
