{% set name = "crontab" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/crontab-{{ version }}.tar.gz
  sha256: 715b0e5e105bc62c9683cbb93c1cc5821e07a3e28d17404576d22dba7a896c92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - crontab
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/josiahcarlson/parse-crontab
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: Parse and use crontab schedules in Python

extra:
  recipe-maintainers:
    - mcs07
    - sanurielf
