{% set name = "crontab" %}
{% set version = "1.0.0" %}
{% set sha256 = "7e9b19bb3abfdf3fbdf9a188207fcc1a27c49347010753c45d47ef7502100ae5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - crontab

about:
  home: https://github.com/josiahcarlson/parse-crontab
  license: LGPL-2.1 or LGPL-3.0
  license_family: LGPL
  license_file: LICENSE3
  summary: Parse and use crontab schedules in Python

extra:
  recipe-maintainers:
    - mcs07
